### ISSUE TITLE
[suggestion] add a command to make a player open a group/personal storage

### ISSUE THREAD

**Issue by The-Nyla** [ChihuyuNetwork/SmartStorage#2]
I want to add a system on my server for players to have a personal storage they can access, but only from a certain area or by using certain items, so I need a way to open a player's personal storage for them without giving them access to the commands, that way I can make items, buttons, etc. that open storage inventories upon use.

possible command syntax: /psopen %player%

This would open the player's personal storage for them.

or /gsopen %player% %storageopen%

This would open a group storage inventory for the player

**Comment by hirosukt** [comment]
Thanks for suggesting. I'll add it at 2.3.0,
